### PR TITLE
C "hello world" example

### PR DESCRIPTION
**Pull request by kzuri**
In reference to #357

### CODE REVIEW

**Comment by kzuri** [comment]
@agbell kindly have a look :)

**Comment by alexcb** [comment]
Thanks for the PR @kzuri , it's looking like a good start. Can you expand on this example to have `main()` reference a function in a different c file, and include a basic unit test of that function using the cunit library?

To install cunit, you should be able to make the following change to the Earthfile:

`RUN apt-get update && apt-get install -y build-essential cmake libcunit1-dev`

**Comment by kzuri** [comment]
Cool @alexcb . I will try 😄

**Comment by kzuri** [comment]
@alexcb how to do i integrate cunit files in `test` folder and `Earthfile`?

**Comment by alexcb** [comment]
I'm not sure what the best way to approach it is, it seems like you'll need another `add_executable` line to tell cmake to reference the `test/*.c` files. Then once cmake compiles a test binary, it could be run via an Earthfile test target.

**Comment by kzuri** [comment]
@alexcb And to be clear, there would be only one Earthfile right?

**Comment by alexcb** [comment]
yeah the single Earthfile that you have could be changed to something like:

```
RUN --mount=type=cache,target=/code/CMakeFiles make
RUN ./fibonacci-test
SAVE ARTIFACT fibonacci AS LOCAL "fibonacci"
```

That way if `./fibonacci-test` fails, then it'll stop the build thus indicating something went wrong with the test.

**Review by alexcb — CHANGES_REQUESTED** [review]
It's no rush, but just wanted to check in to see if you had any luck getting the `fibonacci-test` binary compiled?

**Comment by kzuri** [comment]
This change you suggest I not working well with cunit

`RUN apt-get update && apt-get install -y build-essential cmake libcunit1-dev`

I will update you soon 👍

**Comment by alexcb** [comment]
We are following github's push to rename `master` to `main`, see https://github.com/github/renaming/ for details.

If this PR is ready to be merged, please open a new PR against our `main` branch, as we no longer have a `master` branch. Thanks.

**Pull request closed without merging**
