### PR TITLE
Ignore analytics for --version command

### PR DESCRIPTION
**Pull request by alexcb**
When --version is run, urfav/cli does not invoke the app.Before
function, this causes the config not to be parsed.

If a user had a config option to disable analytics, and ran the
--version flag, it would cause analytics to be reported.

### CODE REVIEW

**Review by vladaionescu — APPROVED** [review]

**Review by vladaionescu — CHANGES_REQUESTED** [review]
Wait... this isn't right.. if the user does not have a config file, it means that we don't collect analytics at all?

**Comment by alexcb** [comment]
we'll default to collecting metrics. The issue is because https://github.com/earthly/earthly/blob/main/cmd/earth/main.go#L579 is not invoked until app.Before() is called. app.Before() is called in regular cases, except for when the `--version` flag is detected.

The other approach would be to run `ParseConfigFile` in `main`. maybe that's the best approach?

**Comment by alexcb** [comment]
oh right, but we can't read the config file without allowing for the `--config` override flag.

**Review by vladaionescu — APPROVED** [review]
:+1:

**Pull request merged**
