### PR TITLE
Remove beta labels from satellites commands

### PR DESCRIPTION
**Pull request by brandonSc**
Removed beta label in satellite commands, and warnings in docs.

### CODE REVIEW

**Comment by brandonSc** [comment]
Before merging, I'm waiting on a few bug fixes and stability patches to go out on the backend. ETA today or tomorrow.

**Review by alexcb — APPROVED** [review]
looks good! don't forget to merge these changes into the docs-0.7 branch.

**Comment by brandonSc** [comment]
> looks good! don't forget to merge these changes into the docs-0.7 branch.

Right! I keep forgetting 🤦

**Comment by brandonSc** [comment]
@alexcb I'm going to remove the docs from the PR and add them in a separate PR to `docs-0.7`

**Comment by brandonSc** [comment]
Docs PR: https://github.com/earthly/earthly/pull/2903/files

**Review by vladaionescu — APPROVED** [review]

**Pull request merged**
