### PR TITLE
Add additional documentation for new contributors

### PR DESCRIPTION
**Pull request by BjoernAkAManf**
Hi,

first of all i want to say that Earthly is a great project.
Knowing from experience how annoying reproducibility can be, i fully agree with the value proposition.

While trying out building earthly, i had some initial problems, which were trivial to solve eventually, but made it harder for me to start working on the source code itself. 

Therefore i propose the following changes to the documentation to improve it.

Happy Hacktoberfest!

Feel free to request any changes you'd like!

### CODE REVIEW

**Comment by vladaionescu** [comment]
Thanks for the initiative @BjoernAkAManf - I'll make some changes on top of your PR before accepting.

**Comment by vladaionescu** [comment]
Hi @BjoernAkAManf - I've included your changes in this new PR: https://github.com/earthly/earthly/pull/412. Thanks for helping us out!

**Comment by BjoernAkAManf** [comment]
Hi @vladaionescu ,
glad it helps! I however would like to ask you to add the "hacktoberfest-accepted" label, as well, since it has been merged 😄 .

Looking forward to test earthly in production for a prototype at work soon.

**Comment by vladaionescu** [comment]
Done!

**Comment by agbell** [comment]
Hi @BjoernAkAManf, thanks for your contributions.  Would you like us to send you an earthly sticker?  If so please send me your address to adam@earthly.dev

**Pull request closed without merging**
