### PR TITLE
Cleaner checkout in Github Action integration example

### PR DESCRIPTION
**Pull request by basilenouvellet**

### CODE REVIEW

**Review by alexcb — APPROVED** [review]
I wasn't familiar `ref` did this, but it looks like it does https://github.com/actions/checkout#checkout-a-different-branch

**Comment by alexcb** [comment]
I just opened https://github.com/earthly/earthly/pull/1851 to make this change in our own tests, if everything goes well we'll merge this PR to update the docs. Thanks for pointing this out.

**Comment by alexcb** [comment]
It turns out there's a slight different between using `ref` and the current `git checkout -b` version, I've opened #1853 to explain the reasoning.

**Comment by basilenouvellet** [comment]
understood, thanks for the explanation

**Pull request closed without merging**
