### PR TITLE
Document buildkit additional args

### PR DESCRIPTION
**Pull request by dchw**

### CODE REVIEW

**Comment by vladaionescu** [comment]
I see additional commits in this PR. Wrong base branch?

Note that you should branch off main since the feature is already released.

**Comment by dchw** [comment]
I branched off main but was merging to next.

I thought docs PRs had to go te next first?

**Comment by vladaionescu** [comment]
> I thought docs PRs had to go to next first?

No.. only if they are documenting unreleased features.

**Comment by dchw** [comment]
So is next docs ony?

**Comment by vladaionescu** [comment]
> So is next docs ony?

Usually yes. Sometimes also examples of new features.

**Pull request closed without merging**
