### PR TITLE
expose earthly env variable

### PR DESCRIPTION
**Pull request by alexcb**
This will prevent having earth create a new installID when running the examples and other earth-in-earth tests.

### CODE REVIEW

**Review by vladaionescu — COMMENTED** [review]
Oh good find.

This won't work unfortunately because the builtin build arg needs to be predeclared by the user using ARG EARTHLY. For our tests it's probably better to add EARTHLY=true in the +docker-earth target, which is used in integration tests.

**Comment by alexcb** [comment]
Right that's a good point. This question might be outside of the scope of this PR, but is there a reason we want to be so explicit with predeclaring these builtin EARTHLY_* args?

**Comment by vladaionescu** [comment]
Yes... because otherwise the varying git hash would bust the cache on every run...

**Comment by alexcb** [comment]
ah right of course. What about always exposing env variables we know won't ever change, like `EARTHLY=true`? That might be a weird case as then we'll have to explain the various edge-cases and that makes documentation more complex.

another idea is to set the ID to unknown when the repohash is unknown. ie.:
```
		if ci {
			installID = fmt.Sprintf("%x", sha256.Sum256([]byte(ciName+repoHash)))
		} else if repoHash == "unknown" {
			installID = "unknown"
		} else {
			installID, err = getInstallID()
			if err != nil {
				installID = "unknown"
			}
		}
```
```

**Comment by vladaionescu** [comment]
I think marking install_id unknown like you suggest is the best idea... it'll also catch any other weird edge cases we're not thinking of.

**Review by vladaionescu — APPROVED** [review]

**Pull request merged**
