### PR TITLE
Syntax highlighting for sublime

### LINKED ISSUE #331: Feature request: Syntax highlighting for Sublime Text
We already have a [TextMate grammar](https://github.com/earthly/earthly/blob/master/contrib/earthfile-syntax-highlighting/syntaxes/earthfile.tmLanguage.json) for VS Code syntax highlighting. Wondering if it's easy to port that into the right format for Sublime Text.

### PR DESCRIPTION
**Pull request by vishnugt**
- This closes #331 
- Added readme with installation steps for Sublime 2 and Sublime 3 and also added a screenshot.
- Refer [this](https://github.com/vishnugt/earthly/tree/master/contrib/earthfile-syntax-highlighting-sublime) for a readable readme

Notes:
- Sublime does not support Textmate grammar in json format, so converted the existing grammar to XML and added it.
- Future changes can be done in the json Textmate grammar and can be converted to XML by using "TextMate Languages" extension in Visual Studio code

### CODE REVIEW

**Comment by agbell** [comment]
Thanks for the PR @vishnugt!  @zedtux you are a sublime user, are you able to test this?

**Comment by zedtux** [comment]
Sure I can test this.

Question: Will you publish a package in order to make it easy to install it?

**Comment by vishnugt** [comment]
@zedtux Thanks for the comments, you're right about file type association.  I missed that part, have fixed it now, so once the plugin is installed Earthfiles will be auto associated with this syntax.

**Review by vladaionescu — APPROVED** [review]
This is awesome @vishnugt! Thank you for the contribution.

Are you willing to also publish this via [these instructions](https://packagecontrol.io/docs/submitting_a_package)? Totally fine if not.

**Comment by vishnugt** [comment]
Hey, thanks for merging!

> Are you willing to also publish this via these instructions? Totally fine if not.
Sure, it's actually quite simple, all we need to do is create a repo with the tmLanguage file and make a pull request to https://github.com/wbond/package_control_channel with very minimal details.
Example PR - https://github.com/wbond/package_control_channel/pull/8019/files

I will be happy to do it, all I will need from your side is to create a repo for the same.

**Comment by vladaionescu** [comment]
Great - here you are: https://github.com/earthly/sublimetext-earthly-syntax

**Comment by zedtux** [comment]
Awesome guys 👍

**Pull request merged**
