### PR TITLE
fix zsh autocompletion

### PR DESCRIPTION
**Pull request by alexcb**
Signed-off-by: Alex Couture-Beil <alex@earthly.dev>

### CODE REVIEW

**Comment by alexcb** [comment]
here's what I did to test this locally
```
alex@mah:~/gh/earthly/earthly$ sudo ./build/linux/amd64/earthly bootstrap
Bootstrapping successful; you may have to restart your shell for autocomplete to get initialized (e.g. run "exec $SHELL")

alex@mah:~/gh/earthly/earthly$ cat /usr/share/bash-completion/completions/earthly
complete -o nospace -C '/home/alex/gh/earthly/earthly/build/linux/amd64/earthly' earthly

$ cat /usr/local/share/zsh/site-functions/_earthly
#compdef _earthly earthly

function _earthly {
    autoload -Uz bashcompinit
    bashcompinit
    complete -o nospace -C '/home/alex/gh/earthly/earthly/build/linux/amd64/earthly' earthly
}

alex@mah:~/gh/earthly/earthly$ ./build/linux/amd64/earthly bootstrap --source bash
complete -o nospace -C '/home/alex/gh/earthly/earthly/build/linux/amd64/earthly' earthly

alex@mah:~/gh/earthly/earthly$ ./build/linux/amd64/earthly bootstrap --source zsh
#compdef _earthly earthly

function _earthly {
    autoload -Uz bashcompinit
    bashcompinit
    complete -o nospace -C '/home/alex/gh/earthly/earthly/build/linux/amd64/earthly' earthly
}
```

**Comment by vladaionescu** [comment]
Could you try to test this on Mac + brew too? Wondering if there's a way to simulate a brew install.

**Comment by alexcb** [comment]
The previous issue was caused since I never tested it via a brew install; looks like we can do this via:

```
➜  Formula git:(master) brew uninstall earthly                  
Uninstalling /usr/local/Cellar/earthly/0.5.5... (7 files, 28.4MB)
➜  Formula git:(master) rm '/usr/local/share/zsh/site-functions/_earthly'
rm: /usr/local/share/zsh/site-functions/_earthly: No such file or directory
➜  Formula git:(master) brew install ./earthly.rb                        
Error: Failed to load cask: ./earthly.rb
Cask 'earthly' is unreadable: wrong constant name #<Class:0x00007fdcb6a61ea0>
Warning: Treating ./earthly.rb as a formula.
==> Downloading https://homebrew.bintray.com/bottles/earthly-0.5.5.big_sur.bottle.tar.gz
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/9218f269da4a3a9b86ebabea9ff1e0b4df48d1c39314c8df7bdb5b0c82b45b7b--earthly-0.5.5.big_sur.bottle.tar.gz
==> Pouring earthly-0.5.5.big_sur.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/earthly/0.5.5: 7 files, 28.4MB
➜  Formula git:(master) cat /usr/local/share/zsh/site-functions
cat: /usr/local/share/zsh/site-functions: Is a directory
➜  Formula git:(master) 
➜  Formula git:(master) 
➜  Formula git:(master) cat /usr/local/share/zsh/site-functions/_earthly 
#compdef _earthly earthly

function _earthly {
    autoload -Uz bashcompinit
    bashcompinit
    complete -o nospace -C '__earthly__' earthly
}
```

I'll test if I can modify the `earthly.rb` formula to reference `https://github.com/earthly/earthly/archive/fix-zsh-autocompletion.zip`

**Comment by alexcb** [comment]
Here's a method for testing homebrew formulas:

step 1: download the git branch, rename it to a version string that matches what homebrew expects, and host it on a local http server:

    wget https://github.com/earthly/earthly/archive/fix-zsh-autocompletion.tar.gz && mv fix-zsh-autocompletion.tar.gz v0.5.5.tar.gz && python3 -m http.server

step2: get the sha256 sum (and replace the IP with your host's ip)

    curl 192.168.0.114:8000/v0.5.5.tar.gz | sha256sum -

step3: update the url and sha in the `earthly.rb` file:

```
diff --git a/Formula/earthly.rb b/Formula/earthly.rb
index 82c0440126..f68c159414 100644
--- a/Formula/earthly.rb
+++ b/Formula/earthly.rb
@@ -1,8 +1,9 @@
 class Earthly < Formula
   desc "Build automation tool for the container era"
   homepage "https://earthly.dev/"
-  url "https://github.com/earthly/earthly/archive/v0.5.5.tar.gz"
-  sha256 "6053b5f6d70f8df1d1c867afeceb41d9ffb2426f8638d585d1770a976352b810"
+  url "http://192.168.0.114:8000/v0.5.5.tar.gz"
+
+  sha256 "b9cc1d1d4dd81b97218af3fe843a254d7b5b2a86635a38d235b5b1b0865a30ec"
   license "BUSL-1.1"
   head "https://github.com/earthly/earthly.git"
```

step4: compile it from source (note that I could only make it work with a full absolute path):

    brew install -s /Users/alex/gh/homebrew/homebrew-core/Formula/earthly.rb

```

step5: test:

```
cat /usr/local/share/zsh/site-functions/_earthly 
#compdef _earthly earthly

function _earthly {
    autoload -Uz bashcompinit
    bashcompinit
    complete -o nospace -C '/usr/local/Cellar/earthly/0.5.5/bin/earthly' earthly
}
```

the full path to earthly matches the symbolic link that's created by homebrew:

```
➜  Formula git:(master) ✗ which earthly
/usr/local/bin/earthly
➜  Formula git:(master) ✗ ls -la /usr/local/bin/earthly
lrwxr-xr-x  1 alex  admin  35  9 Mar 12:26 /usr/local/bin/earthly -> ../Cellar/earthly/0.5.5/bin/earthly
```

and finally a tab-tab example:

```
➜  Formula git:(master) earthly --a
--allow-privileged  --artifact          --auth-token      
```

**Review by vladaionescu — APPROVED** [review]

**Pull request merged**
