### PR TITLE
rename Load to current utilization

### PR DESCRIPTION
**Pull request by alexcb**
This is to avoid load being misinterpreted as "loading data".

Signed-off-by: Alex Couture-Beil <alex@earthly.dev>

### CODE REVIEW

**Review by vladaionescu — COMMENTED** [review]
Can you make this consistent across - e.g. https://github.com/earthly/earthly/blob/main/buildkitd/buildkitd.go#L863

**Comment by alexcb** [comment]
How does this look?

I wasn't sure about renaming `Buildkit is currently under significant load` to `Buildkit is currently under significant utilization` though.

**Comment by vladaionescu** [comment]
See also the link I provided above

**Comment by alexcb** [comment]
> See also the link I provided above

Sorry, misread the request. I pulled that string out into a common util since it's referenced across multiple packages now.

**Review by vladaionescu — APPROVED** [review]

**Pull request merged**
