### PR TITLE
Use the SHA that has the timeout changes in it.

### PR DESCRIPTION
**Pull request by dchw**
Bump the SHA so we can use the timeout options.

### CODE REVIEW

**Review by vladaionescu — APPROVED** [review]
Mind updating go.mod too? We keep them in sync typically (even though it probably doesn't matter in this case).

**Review by alexcb — CHANGES_REQUESTED** [review]
did you use the `+update-buildkit` target: https://github.com/earthly/earthly/blob/main/Earthfile#L50 as outlined under https://github.com/earthly/earthly/blob/main/CONTRIBUTING.md#updates-to-buildkit-or-fsutils ?

This should handle both the `buildkit/Earthfile` and `go.{mod,sum}` files.

**Comment by dchw** [comment]
I did run that target, I didnt see those changes though...

**Review by alexcb — APPROVED** [review]

**Comment by alexcb** [comment]
> ~I did run that target, I didnt see those changes though...~
> 
> I ran `./buildkit+update-buildkit`. sob

that's some good feedback, I updated the buildkit target name in #2084 to make it less confusing.

**Pull request merged**
