### PR TITLE
Secret migration command

### PR DESCRIPTION
**Pull request by mikejholly**
Adds a new "secret migration" command that copies secrets from an existing organization to a target project (under the same or different organization).

`earthly preview secrets --org <dest-organization> --project <dest-project> migrate <source-organization>`

Example:
`earthly preview secrets --org mikeorg --project mikeproject migrate earthly-technologies`

By default the command prints out `.`'s but users can pass `--verbose` to review all copied secrets.

```
➜  earthly git:(mh/secret-migrate) ✗ earthly preview secrets --org mikeorg --project mikeproject migrate earthly-technologies
Copying 103 secrets to mikeproject
.......................................................................................................
103 secrets migrated successfully!
➜  earthly git:(mh/secret-migrate) ✗ earthly preview secrets --org mikeorg --project mikeproject migrate -v earthly-technologies
Copying 103 secrets to mikeproject
Copying secret "/earthly-technologies/auth/dev/private-key" to "/mikeorg/mikeproject/auth/dev/private-key"
Copying secret "/earthly-technologies/auth/dev/public-key" to "/mikeorg/mikeproject/auth/dev/public-key"
Copying secret "/earthly-technologies/auth/production/private-key" to "/mikeorg/mikeproject/auth/production/private-key"
Copying secret "/earthly-technologies/auth/production/private-key_64" to "/mikeorg/mikeproject/auth/production/private-key_64"
Copying secret "/earthly-technologies/auth/production/public-key" to "/mikeorg/mikeproject/auth/production/public-key"
Copying secret "/earthly-technologies/auth/production/public-key_64" to "/mikeorg/mikeproject/auth/production/public-key_64"
Copying secret "/earthly-technologies/auth/staging/private-key" to "/mikeorg/mikeproject/auth/staging/private-key"
Copying secret "/earthly-technologies/auth/staging/private-key_64" to "/mikeorg/mikeproject/auth/staging/private-key_64"
Copying secret "/earthly-technologies/auth/staging/public-key" to "/mikeorg/mikeproject/auth/staging/public-key"
Copying secret "/earthly-technologies/auth/staging/public-key_64" to "/mikeorg/mikeproject/auth/staging/public-key_64"
Copying secret "/earthly-technologies/auth/stg/private-key" to "/mikeorg/mikeproject/auth/stg/private-key"
...
```

### CODE REVIEW

**Review by alexcb — APPROVED** [review]
looks good.

I wonder if some users would like a `--dry-run` option to see where they will be written to?

**Comment by alexcb** [comment]
or perhaps an interactive Y/N confirmation prompt before actually doing the writes?

**Comment by mikejholly** [comment]
Added a `--dry-run` option. Good idea.

**Review by alexcb — APPROVED** [review]

**Review by vladaionescu — COMMENTED** [review]
Some minor comments after the fact...

**Pull request merged**
