### PR TITLE
Try to fix `Some image digests do not match across tags in multi-platform builds`

### LINKED ISSUE #2183: Some image digests do not match across tags in multi-platform builds
Given this sample Earthfile:
```
VERSION 0.6

FROM alpine:3.16

WORKDIR /tmp

all:
  BUILD \
    --platform=linux/amd64 \
    --platform=linux/arm/v7 \
    --platform=linux/arm64 \
    +docker-release

build:
  RUN echo "Hi!" > /tmp/hello
  SAVE ARTIFACT /tmp /tmp

docker-release:
  COPY +build/tmp /tmp

  SAVE IMAGE --push \
    docker.io/dchw/zwave-js-server:1 \
    docker.io/dchw/zwave-js-server:2 \
    docker.io/dchw/zwave-js-server:3 \
    docker.io/dchw/zwave-js-server:4 \
    docker.io/dchw/zwave-js-server:5
```

And run `earthly --ci --push +all`.

This _should_ produce 5 tags, with three platforms each; and the image digests should match up per platform across all the tags. Instead, some do and some do not. It appears to be random which are mismatched. An example, for clarity (the colored parts should be expected to match):
image

I found that any of the following fixed this sample `Earthfile`:
* remove the WORKDIR command, OR:
* remove the second argument of the SAVE ARTIFACT, OR:
* copy the file (/tmp/hello) instead of the directory (change all /tmp to /tmp/hello)
  * also holds true for only the COPY line (change it to COPY +build/tmp/hello /tmp/hello)
* remove the copy alltogether
* run it without `--save-inline-cache`

I tested this all the way back to Earthly v0.6.14, and found the problem was still present for this example.

### PR DESCRIPTION
**Pull request by n-rodriguez**
Try to fix #2183

### CODE REVIEW

**Comment by idelvall** [comment]
Hi @n-rodriguez, please set the PR as a draft until it is ready for review

**Review by alexcb — CHANGES_REQUESTED** [review]
please take a look at https://github.com/earthly/earthly/blob/main/CONTRIBUTING.md#running-tests to see how to run tests.

it also contains information for PRs that touch the buildkit fork.

**Comment by n-rodriguez** [comment]
why closing the pr?

**Comment by n-rodriguez** [comment]
that's not very fair...

**Comment by n-rodriguez** [comment]
i'm still working on it

**Comment by alexcb** [comment]
I closed it since we never heard back from you, nor did there appear to be any activity on the PR.

is there a corresponding PR for the buildkit repo that you want to submit?

**Pull request closed without merging**
