### PR TITLE
Reverting integration example to use docker in docker 

### PR DESCRIPTION
**Pull request by agbell**
Reverting integration example to use docker in docker to work around #422

### CODE REVIEW

**Comment by vladaionescu** [comment]
Should the equivalent docs also be updated?

**Comment by agbell** [comment]
> Should the equivalent docs also be updated?

updated, though I am sad to lose the example of auto-installing docker tools.  I will revert this once #422 is addressed in windows.

**Review by vladaionescu — APPROVED** [review]
Looks good - might need to wait for master CI to be fixed and rebase to make sure tests pass.

**Comment by vladaionescu** [comment]
> Looks good - might need to wait for master CI to be fixed and rebase to make sure tests pass.

Master is fixed now. I'll merge as is.

**Pull request merged**
