### PR TITLE
Fix host test use of grep

### PR DESCRIPTION
**Pull request by mikejholly**
`acbgrep` isn't available here. Plus, the other tests in this file just use `grep`.

### CODE REVIEW

**Review by alexcb — APPROVED** [review]

**Comment by alexcb** [comment]
sorry about that :(

**Comment by alexcb** [comment]
looks like you need a `earthly ./ast/tests+update-all` too

**Comment by alexcb** [comment]
another (longer term) idea: should we stop using the default `alpine` image and instead have an `earthly/alpine-base` image that we include other things we sometimes need in our tests?

**Comment by mikejholly** [comment]
> another (longer term) idea: should we stop using the default `alpine` image and instead have an `earthly/alpine-base` image that we include other things we sometimes need in our tests?

Sounds reasonable.

**Pull request merged**
