### PR TITLE
Allow DIND auto install on Amazon Linux

### PR DESCRIPTION
**Pull request by dchw**
This will let you do a `WITH DOCKER` in an Amazon Linux container. This is especially advantageous for using other containers in combination with "amazon/aws-cli:<version>"

Amazon Linux 1 and 2 are supported.

### CODE REVIEW

**Review by vladaionescu — APPROVED** [review]
Very cool!

**Review by vladaionescu — APPROVED** [review]

**Comment by alexcb** [comment]
@dchw can you try rebaseing this off `origin/main` to see if it fixes the tests.

**Comment by dchw** [comment]
I thought I had initially based off main, but I will give it a shot

**Comment by dchw** [comment]
Looks like I went off main before we were fully on main:

<pre>*   <font color="#CC0000">8a818c5</font> -<font color="#C4A000"> (HEAD -&gt; core/add-dind-amazonlinux, origin/core/add-dind-amazonlinux)</font> Merge branch &apos;main&apos; into core/add-dind-amazonlinux <font color="#4E9A06">(2 minutes ago) </font><font color="#729FCF"><b>&lt;Corey Larson&gt;</b></font>
<font color="#CC0000">|</font><font color="#4E9A06">\</font>  
<font color="#CC0000">|</font> * <font color="#CC0000">43851f7</font> -<font color="#C4A000"> (origin/main, main)</font> include main branch in Earthfiles <font color="#4E9A06">(22 minutes ago) </font><font color="#729FCF"><b>&lt;Alex Couture-Beil&gt;</b></font>
* <font color="#4E9A06">|</font> <font color="#CC0000">f1fbcb1</font> - Auto-install docker in amazonlinux <font color="#4E9A06">(29 minutes ago) </font><font color="#729FCF"><b>&lt;Corey Larson&gt;</b></font>
<font color="#4E9A06">|/</font>  
* <font color="#CC0000">72c741e</font> - renamed buildkit earthly-master to earthly-main <font color="#4E9A06">(34 minutes ago) </font><font color="#729FCF"><b>&lt;Alex Couture-Beil&gt;</b></font>
</pre>

**Comment by alexcb** [comment]
I fixed another issue with `main`, and just merged it into this PR. let's see if this fixes it.

**Pull request merged**
