### PR TITLE
WIP: Add Django example

### PR DESCRIPTION
**Pull request by raisultan**

### CODE REVIEW

**Review by shreayan98c — COMMENTED** [review]
The DB used in this Django example is the sqlite3 database but in the docs it is mentioned to use an example having the Postgres DB.

**Comment by raisultan** [comment]
@shreayan98c link to docs?

**Comment by shreayan98c** [comment]
> @shreayan98c link to docs?

Issue #343 states to include a Django + Postgres example. Hence I suggest changing the sqlite3 DB to Postgres DB.

**Comment by raisultan** [comment]
> > @shreayan98c link to docs?
> 
> Issue #343 states to include a Django + Postgres example. Hence I suggest changing the sqlite3 DB to Postgres DB.

yep, my fault skipped the title 😢, will correct it now

**Comment by shreayan98c** [comment]
> > > @shreayan98c link to docs?
> > 
> > 
> > Issue #343 states to include a Django + Postgres example. Hence I suggest changing the sqlite3 DB to Postgres DB.
> 
> yep, my fault skipped the title 😢, will correct it now

If you need help, let me know. I can help with the same.

**Comment by agbell** [comment]
Good progress @raisultan.  What I'd like to see ideally is using postgres, and with a test that hits the database and earth build target that starts postgres, runs the tests and stops it.  I think this mirrors how in the real world someone would run tests that hit the database.

**Comment by raisultan** [comment]
> Good progress @raisultan. What I'd like to see ideally is using postgres, and with a test that hits the database and earth build target that starts postgres, runs the tests and stops it. I think this mirrors how in the real world someone would run tests that hit the database.

Got it, on it 😄

**Comment by alexcb** [comment]
We are following github's push to rename `master` to `main`, see https://github.com/github/renaming/ for details.

If this PR is ready to be merged, please open a new PR against our `main` branch, as we no longer have a `master` branch. Thanks.

**Pull request closed without merging**
