### PR TITLE
Bump dind docker to 23.0.6-r7

### PR DESCRIPTION
**Pull request by mikejholly**
Sadly, a `--DOCKER_VERSION=~23.0.6` attempt led to push failures.

### CODE REVIEW

**Review by alexcb — APPROVED** [review]

**Comment by mikejholly** [comment]
`amazon-elastic-container-registry` is failing but I'll address that in another PR.

**Review by idodod — COMMENTED** [review]
We should update the referenced tag in the tests and docs:
https://github.com/earthly/earthly/pull/3445/files
https://github.com/earthly/earthly/pull/3432/files

**Comment by mikejholly** [comment]
@idodod Ok. Updating for every RC is becoming a hassle. Hopefully `23.0.6` is released soon.

**Comment by idodod** [comment]
> @idodod Ok. Updating for every RC is becoming a hassle. Hopefully `23.0.6` is released soon.

I looked into using Renovate for this. Actually not using the RC will help with that

**Pull request merged**
